### ISSUE TITLE
Closing the first-launch dialog and restarting the app will cause Speek to never connect to the network.

### ISSUE THREAD

**Issue by Jonas-Sander** [Speek-App/Speek#1]
## Describe the bug
When first opening Speek a dialog with the options "Launch Speek.Chat" and "Configure Network" is shown.   
If this dialog is closed (no option was selected) and Speek is launched again then the application will open the main window but never connect to the network - it will display "Connecting 0%" forever. Relaunching doesn't help, only reinstalling Speek.

I only tested this on Windows, don't know if this occures on other platforms.

## Steps to reproduce the bug
0. (Deinstall Speek if installed.)
1. Install Speek.
2. Open Speek.
3. Close the app after the first-launch window is displayed. 
4. Open Speek again.

## Current _broken_ behavior
The application will display "Connecting (0%)" indefinitely.

## Expected behavior
The first-launch window should open again or the application should connect properly.

## Screenshots, videos or logs
https://user-images.githubusercontent.com/29028262/157549132-f046293e-5356-4375-83ee-76104dee487b.mp4

## Tested device

- Device: PC
- OS: Windows 10
- App type: Windows Store app
- App version: 1.5.0.0

**Comment by Speek-App** [comment]
Thanks a lot for the detailed bug report. Will look into it right away.

**Comment by Speek-App** [comment]
Should be fixed already. The fix will be included in the next update we publish on the Microsoft store. 
Thanks again for pointing this issue out. I really appreciate it.
