### ISSUE TITLE
connections have failed

### ISSUE THREAD

**Issue by o9c4** [Speek-App/Speek#13]
May 12 19:20:15.000 [warn] Problem bootstrapping. Stuck at 5% (conn): Connecting to a relay. (Connection timed out [WSAETIMEDOUT ]; TIMEOUT; count 21; recommendation warn; 
May 12 19:20:15.000 [warn] 20 connections have failed:
May 12 19:20:15.000 [warn]  20 connections died in state connect()ing with SSL state (No SSL object)

**Comment by Speek-App** [comment]
That is indeed really weird.

Maybe Tor is being blocked by your network? Is the Tor Browser working for you?
If that is the case, can you try to use a [bridge](https://bridges.torproject.org/bridges) in the Tor settings.

Alternatively, you can try to delete the tor folder from the config location. You can find it, depending on your OS, here: 
```
Linux: ~/.config/speek
Windows: C:/Users/<USER>/AppData/Local/speek
MacOS: ~/Library/Preferences/<APPNAME>
```

**Comment by o9c4** [comment]
Tor Browser is blocked in country where I am working now, but we use bridges and its working well, but the Speek.Chat is not working anyway. Maybe I should set up Advanced Network Configuration somehow? 

Can't find that folder: Windows: C:/Users/<USER>/AppData/Local/speek
