### ISSUE TITLE
No more HSDir to inquiry

### ISSUE THREAD

**Issue by Farmer8843** [Speek-App/Speek#20]
For the past two days, I have received the same error after logging in and trying to add a friend. The login seems to work fine as it gets to 100% bootstrapped, then it proceeds to say nothing but the same message after.

May 26 19:55:44.000 [notice] Bootstrapped 100% (done): Done
May 26 19:55:56.000 [notice] Closed 1 streams for service [scrubbed].onion for reason resolve failed. Fetch status: No more HSDir available to query.

Tried a bridge but the program just would automatically close out. I'm on Linux Mint 20.3 Una.

**Comment by Speek-App** [comment]
Thanks for opening an issue.

Can you try the[ newest version](https://github.com/Speek-App/Speek/releases/tag/v1.7.0-pre-release) of Speek? Bridges should work with that one.

**Comment by Farmer8843** [comment]
I got bridges to work with the newest version of Speek. But now I'm trying to log back in again and it seems to get stuck at connecting 10%. My internet seems to be working fine though.

**Comment by Speek-App** [comment]
Which bridges are you currently using? Please note that currently obfs4 bridges are not supported. Use [those](https://bridges.torproject.org/bridges) instead.

**Comment by Farmer8843** [comment]
I cannot even log in to use bridges, currently. It still gets stuck at connecting 10%. I'm using the newest version as well.

**Comment by Speek-App** [comment]
That's really weird. Can try to delete the tor folder from the config location. You can find it, depending on your OS, here: 

Linux: ~/.config/speek
Windows: C:/Users/<USER>/AppData/Local/speek
MacOS: ~/Library/Preferences/<APPNAME>
