### ISSUE TITLE
Empty main Window ?

### ISSUE THREAD

**Issue by garbage314** [Speek-App/Speek#27]
Hi,

After a fresh install, I just get an empty windows when launching. No buttons, menus, nothing ?
<img width="1021" alt="speek" src="https://user-images.githubusercontent.com/38316289/176880487-65008e30-cdf2-4c83-a6c1-a2dbef4184bd.png">
)
I cant' get how to use this. I'm on Windows7

Thanks for help

**Comment by Speek-App** [comment]
Thanks or opening an issue!

That issue has already been fixed. You can find a pre-release with the fix [here](https://github.com/Speek-App/Speek/releases/tag/v1.6.1-pre-release)
