### ISSUE TITLE
After the default setting button, the window opens and say only "Online" with the logo at center of the screen

### ISSUE THREAD

**Issue by clmwith** [Speek-App/Speek#3]
All is in the title.
I'm using : Speek.Chat-1.6.0-x86_64.AppImage (on Ubuntu 20.04 64bits)

Doesn't work at all.
The console output: 
Gtk-Message: 15:44:59.634: Failed to load module "appmenu-gtk-module"
QIODevice::read (QFile, "/home/xxx/.config/speek/tor/torrc"): device not open
qrc:/ui/MainWindow.qml:47:9: Unable to assign [undefined] to bool
qrc:/ui/MainWindow.qml:47:9: Unable to assign [undefined] to bool
qrc:/ui/main.qml:182: TypeError: Cannot read property 'themeColor' of null
qrc:/ui/main.qml:195: TypeError: Cannot read property 'themeColor' of null
qrc:/ui/main.qml:191: TypeError: Cannot read property 'themeColor' of null
qrc:/ui/main.qml:192: TypeError: Cannot read property 'themeColor' of null
qrc:/ui/main.qml:183: TypeError: Cannot read property 'themeColor' of null

At the second lauch it display only : 
Gtk-Message: 15:58:35.040: Failed to load module "appmenu-gtk-module"
qrc:/ui/MainWindow.qml:47:9: Unable to assign [undefined] to bool

Same behaviour with Windows version.

What cat be done ?

Thank's

**Comment by Speek-App** [comment]
Thanks for opening an issue!
That's really weird, especially as it's not even working on Windows for you. I just tested it on Ubuntu 20.04.3 LTS and it worked fine. Can you let me know which Windows version you are using (7, 8, 8.1, 10). Also, can you maybe post a screenshot of the application.

**Comment by clmwith** [comment]
Hello,

I'm using Ubuntu-mate 20.04.3 (updated)

more /etc/apt/sources.list
# deb cdrom:[Ubuntu-MATE 20.04.1 LTS _Focal Fossa_ - Release amd64 (20200731)]/ focal main multiverse restricted universe
deb http://fr.archive.ubuntu.com/ubuntu/ focal main restricted
deb-src http://fr.archive.ubuntu.com/ubuntu/ focal main restricted
...

uname -a
Linux trucmuch 5.4.0-105-generic #119-Ubuntu SMP Mon Mar 7 18:49:24 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

![Capture du 2022-04-01 17-09-59](https://user-images.githubusercontent.com/43881698/161291393-a0be1d44-dcd9-4824-9270-6c6a66202ef3.png)

**Comment by clmwith** [comment]
You have closed the issue without any information...

is there a new version to test ?

Thank's

**Comment by Speek-App** [comment]
That issue has been fixed within the most recent commit. Sorry for not making a pre-release immediately.
You can find a pre-release with only the fix (no other new features) [here](https://github.com/Speek-App/Speek/releases/tag/v1.6.1-pre-release) 

Thanks again for opening this issue.
