### ISSUE TITLE
Could using the tor network be optional?

### ISSUE THREAD

**Issue by Snippet24816** [Speek-App/Speek#32]
Sorry I'm not expert on this area, but for example using a VPN instead?

**Comment by shayaknyc** [comment]
From what little I was able to understand, the way it works is that every client is essentially running it's own "hidden service" on the TOR network. You are unable to use this without connecting to TOR.

**Comment by Speek-App** [comment]
> From what little I was able to understand, the way it works is that every client is essentially running it's own "hidden service" on the TOR network. You are unable to use this without connecting to TOR.

Yes, that is basically correct. As a result, it cannot be used without Tor.

If you only want to prevent others from knowing that you're using Tor, you can use a [bridge](https://bridges.torproject.org/bridges) or a VPN.
