### ISSUE TITLE
On Windows 10 and on Ubuntu 20.04 , we only see "en ligne" (French environment).

### ISSUE THREAD

**Issue by ludetie** [Speek-App/Speek#7]
Hello,
After starting, on Windows 10 and on Ubuntu 20.04 , we only see "en ligne" (French environment).
see below screenshot:
![image](https://user-images.githubusercontent.com/91374123/161706669-52e8382b-ad0e-45ac-91b1-bb385fd2c10e.png)

**Comment by Speek-App** [comment]
Thanks for opening an issue!
That issue has been fixed within the most recent commit (copy of #3). Sorry for not making a pre-release immediately.
You can find a pre-release with only the fix (no other new features) [here](https://github.com/Speek-App/Speek/releases/tag/v1.6.1-pre-release)
