### ISSUE TITLE
Speek stops when i try to write bridge into it.

### ISSUE THREAD

**Issue by Atabiy** [Speek-App/Speek#9]
Tor is banned in my country so I need to use bridges. When app starts it gives me opportunity to set bridges using "Advanced network configuration". But when i tried to enter the bridge (in this format:  obfs4 207.148.108.221:443 7259F29EC35E385B25D1DD56A3B39B76BBE63940 cert=aMu33DOPGFQsjgLZ7JtKB6Eysn9kaN4ubcWbi2zsO+rAORC1eKDrDiGqXqkJD8ZLgY25QA iat-mode=0) app just said "This behavior is NOT supported!" and then stopped. 
![image](https://user-images.githubusercontent.com/86558058/162573394-8395270c-2082-47be-834c-d96941213819.png)
![image](https://user-images.githubusercontent.com/86558058/162573405-3e7dd041-b060-48ee-b877-bddc8b32665c.png)

**Comment by Speek-App** [comment]
Thanks a lot for opening this issue.
This should be resolved with the latest commit. I will later add a pre-release with this fix applied.

In addition, currently obfs4 bridges are not supported. Use [those](https://bridges.torproject.org/bridges) instead, although this is not related to the crash reported here.
